GET http://localhost:3000/products?keyword=테스트

###

GET http://localhost:3000/products/5

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "images":["https://avatars.githubusercontent.com/u/139575548?v=4"],
    "tags":["프로필 이미지"],
    "price": 5000,
    "description": "잠온다 자주 사용하는 프로필 이미지입니다.",
    "name": "테스트"
}

###

PATCH  http://localhost:3000/products/1
Content-Type: application/json

{
    "images":["https://avatars.githubusercontent.com/u/139575548?v=4"],
    "tags":["프로필 이미지"],
    "price": 10000,
    "description": "가격을 수정했습니다.",
    "name": "프로필"
}

###
DELETE http://localhost:3000/products/6786c263e20da353a1ea122e