GET http://localhost:3333/article

###

GET http://localhost:3333/article/1fa9eca6-9699-4778-91a6-c34f7a7859f5
###

POST http://localhost:3333/article
Content-Type: application/json

 {
  "nickname": "무념무상판다",
  "title": "뭐 좀 사실 분",
  "content": "뭐 팔지 미정",
  "image": "https://cdn.pixabay.com/photo/2015/10/31/12/41/sale-1015710_1280.jpg"
 }

###

PATCH http://localhost:3333/article/1fa9eca6-9699-4778-91a6-c34f7a7859f5
Content-Type: application/json

{
  "nickname": "귀여운판다",
}

###

DELETE http://localhost:3333/article/787b4aa1-4a8b-4f76-8b0d-556d24d4f58e