GET http://localhost:8000/product

###
 
#data: {
#  title: "iPhone 15 중고 팝니다",
#  contents: "사용한지 3개월 된 아이폰 15 판매합니다.",
#  img: "iphone_sale.jpg",
#  like: 5,
#  userId: user1.id,
#},

POST http://localhost:8000/bulletinBoard?id=72ea9f7e-e141-4828-a200-f3376b3321c4
Content-Type: application/json


{
  "title": "첫게시글제목", 
  "contents": "첫게시글내용"
}

