export const PRODUCTS = [
  {
    name: "물",
    description: "깨끗하고 맛있는 물입니다.",
    price: 5000,
    tags: ["음식", "생활용품"],
    images: [],
    favorite: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "컴퓨터",
    description: "최신형 컴퓨터입니다.",
    price: 500000,
    tags: ["전자기기", "컴퓨터"],
    images: [],
    favorite: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "책",
    description: "베스트셀러이고 한 번만 읽은 책입니다.",
    price: 10000,
    tags: ["도서", "취미"],
    images: [],
    favorite: 94,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "화장품",
    description: "미개봉 색조 화장품입니다.",
    price: 6000,
    tags: ["미용"],
    images: [],
    favorite: 24,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "달력",
    description: "2025년 은행 달력입니다.",
    price: 5000,
    tags: ["사무용품", "문구", "새해"],
    images: [],
    favorite: 77,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "화장지",
    description: "잘풀리는 집 화장지입니다.",
    price: 2000,
    tags: ["생활용품", "화장지"],
    images: [],
    favorite: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "거울",
    description: "한쪽은 3배 크게 볼 수 있는 거울입니다.",
    price: 3000,
    tags: ["미용", "생활용품"],
    images: [],
    favorite: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "마우스",
    description: "최신형 미개봉 마우스입니다.",
    price: 30000,
    tags: ["전자기기", "컴퓨터"],
    images: [],
    favorite: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "베개",
    description: "한 번만 쓴 경추베개입니다.",
    price: 20000,
    tags: ["침구", "생활용품"],
    images: [],
    favorite: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "파우치",
    description: "화장품이나 생활용품을 담을 수 있는 파우치입니다.",
    price: 4000,
    tags: ["미용", "생활용품"],
    images: [],
    favorite: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "슬리퍼",
    description: "실내용 슬리퍼입니다.",
    price: 10000,
    tags: ["생활용품", "신발"],
    images: [],
    favorite: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "스피커",
    description: "블루투스 스피커입니다.",
    price: 600000,
    tags: ["전자기기", "음향"],
    images: [],
    favorite: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "커텐",
    description: "공부할 때 좋은 암막 커텐입니다.",
    price: 70000,
    tags: ["인테리어", "생활용품"],
    images: [],
    favorite: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "카페트",
    description: "집 분위기를 바꿔주는 카페트입니다.",
    price: 40000,
    tags: ["인테리어", "생활용품"],
    images: [],
    favorite: 31,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "선풍기",
    description: "지난 여름에 새로 샀던 선풍기입니다.",
    price: 10000,
    tags: ["전자기기", "여름"],
    images: [],
    favorite: 54,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "협탁",
    description: "침대 옆에 두고 쓰는 협탁입니다.",
    price: 200000,
    tags: ["인테리어", "수납"],
    images: [],
    favorite: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "가방",
    description: "두 번만 쓴 백팩 가방입니다.",
    price: 5000,
    tags: ["패션", "백팩"],
    images: [],
    favorite: 67,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "필통",
    description: "새로 사고 한 번도 안쓴 필통입니다.",
    price: 5000,
    tags: ["문구", "새학기"],
    images: [],
    favorite: 43,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "세탁기",
    description: "21년형 드럼 세탁기입니다.",
    price: 300000,
    tags: ["가전제품", "이사"],
    images: [],
    favorite: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "조끼",
    description: "겨울에 따뜻하게 입을 수 있는 조끼입니다.",
    price: 30000,
    tags: ["패션", "겨울"],
    images: [],
    favorite: 24,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "의자",
    description: "허리를 보호해주는 책상용 의자입니다.",
    price: 20000,
    tags: ["인테리어", "생활용품"],
    images: [],
    favorite: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "퍼즐",
    description: "심심할 때 즐겁게 할 수 있는 퍼즐입니다.",
    price: 4000,
    tags: ["취미", "퍼즐"],
    images: [],
    favorite: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "매트리스",
    description: "꿀잠 잘 수 있는 매트리스입니다.",
    price: 100000,
    tags: ["침구", "인테리어"],
    images: [],
    favorite: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "TV",
    description: "최신형 스마트 TV입니다.",
    price: 500000,
    tags: ["전자기기", "가전제품"],
    images: [],
    favorite: 58,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
