# 게시글 테스트

# 게시글 목록 불러오기
GET http://localhost:8000/articles

###

#게시글 목록 불러오기 - 쿼리 테스트
GET http://localhost:8000/articles?sort=favorite

###

#게시글 상세 조회
GET http://localhost:8000/articles/c82c0cc0-3e25-4311-853a-4c3b57ccff23

###

#게시글 등록
POST http://localhost:8000/articles
Content-Type: application/json

{
  "title": "테스트",
  "content": "테스트~~"
}

###

#게시글 수정
PATCH http://localhost:8000/articles/d160c700-9823-462c-83de-2117953d2388
Content-Type: application/json

{
    "content": "~~",
    "image": "test"
}

###

#게시글 삭제
DELETE http://localhost:8000/articles/d160c700-9823-462c-83de-2117953d2388