# 상품 테스트

#상품 목록 불러오기
GET http://localhost:8000/products

###

#상품 목록 불러오기 - 쿼리 테스트
GET http://localhost:8000/products?sort=favorite&keyword=생필품

###

#상품 상세 조회
GET http://localhost:8000/products/0daedc64-296e-4a19-90ad-e120d1204a57

###

#상품 등록
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "보스 헤드셋",
  "description": "~~",
  "price": 100000,
  "tags" : ["헤드셋","보스"]
}

###

#상품 수정
PATCH http://localhost:8000/products/771f588a-4fb7-45ac-8fa7-cf7c8d99a43c
Content-Type: application/json

{
    "tags" : ["보스 헤드셋", "헤드셋"]
}

###

#상품 삭제
DELETE http://localhost:8000/products/0daedc64-296e-4a19-90ad-e120d1204a57